mysql:
    container_name: supplier_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - "3306:3306"
    volumes:
        - ./logs/mysql:/var/log/mysql/
        - ./data:/var/lib/mysql
#        - ./config/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
        - MYSQL_DATABASE=supplier
        - MYSQL_PASSWORD=supplier
        - MYSQL_ROOT_PASSWORD=supplier
        - MYSQL_USER=root

php:
    container_name: supplier_php
    build: ./api
    dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=supplier
    links:
      - mysql

nginx:
    container_name: supplier_nginx
    image: nginx:1.13
    ports:
      - "8001:80"
    volumes:
      - ./api:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx/
    links:
      - php